### PR TITLE
fix: last header was lost if LF LF (intead of CRLF CRLF)

### PR DESCRIPTION
**Pull request by dportabella**

### CODE REVIEW

**Comment by dportabella** [comment]
You can try it also on a website. For this page: http://www.ipc.com/
HttpResponse does not contain the last header (Content-Type).

**Comment by dportabella** [comment]
I see that you added this for the 1.2.0 Release.
But I see the master is 1.1.8, and there is a brunch 2.x. 
When do you expect to release 1.2.0?

**Comment by kris-sigur** [comment]
There are no concrete plans at this time for the next release. I just added it to 1.2.0 to make sure this wouldn't be overlooked when the time came. If 2.0.0 ends up being the next release, it may get shifted to it. We may also do a 1.1.9 maintenance release and this could be a candidate for that as well.

**Comment by dportabella** [comment]
any news on publishing this? you think it will be next week, next month or next year?

**Pull request merged**
