### PR TITLE
Make canonicalizer be able to strip session id params even if they ar…

### PR DESCRIPTION
**Pull request by vonrosen**
…e the first params in the query string. And add session id strip test. And change IAURLCanonicalizer.java to ensure that if after transformations on the query string have completed and the query is empty, there is not a ? added to the end of the url.

### CODE REVIEW

**Comment by johnerikhalse** [comment]
Will this require reindexing CDX'es?

If that's the case I will propose this goes into at least a minor release, or maybe a major release, and not into a bugfix release.

**Comment by kris-sigur** [comment]
Yes, this should probably be deferred to 1.2 as it changes existing behavior.

Alternatively, if this is an IA only class, perhaps it should be deprecated?

**Comment by johnerikhalse** [comment]
After reviewing OWB, it seems to me that the default configuration is not using IAURLCanonicalizer. The exception is CDX-Server, but since using CDX-Server is not the default at the moment, I think this PR is ok for the next bugfix release.

**Comment by kris-sigur** [comment]
Merged, mostly on the understanding that only IA uses this. Canonicalization really needs to be better standardized.

**Pull request merged**
