### PR TITLE
Move missing unit tests over from Heritrix3

### PR DESCRIPTION
**Pull request by MohammedElsayyed**
This fixes issue #25.

### CODE REVIEW

**Comment by MohammedElsayyed** [comment]
The following unit test already exists in webarchive-commons:
/commons/src/test/java/org/archive/io/arc/ARCReaderFactoryTest.java

Because
/modules/src/test/java/org/archive/modules/writer/ARCWriterProcessorTest.java
/modules/src/test/java/org/archive/modules/writer/WARCWriterProcessorTest.java
don't exits, I don't include them.

**Comment by ldko** [comment]
Thanks, Mohamed. This looks good to me.  Thanks for doing the related [Heritrix PR](https://github.com/iipc/heritrix3/pull/4) too! :+1:

**Comment by MohammedElsayyed** [comment]
I moved unit tests from [iipc/Heritrix3](https://github.com/iipc/heritrix3) not from [ia/Heritrix3](https://github.com/internetarchive/heritrix3), so what I am going to do is as follows:

1. Make sure unit tests code-base moved to [iipc/webarchive-commons](https://github.com/iipc/webarchive-commons) are identical to ones in [ia/Heritrix3](https://github.com/internetarchive/heritrix3).
2. Recheck unit tests in [ia/Heritrix3](https://github.com/internetarchive/heritrix3) which are not moved over to [iipc/webarchive-commons](https://github.com/iipc/webarchive-commons).
 2.1. If there are ones not moved over, then move them.
 2.2. Open an issue in [ia/Heritrix3](https://github.com/internetarchive/heritrix3) for deleting them. 
 2.3. Create a PR for removal.

**Comment by MohammedElsayyed** [comment]
I rechecked and everything is perfect :+1:

**Pull request merged**
